### ISSUE TITLE
Add the helplink for Image Annotation

### ISSUE THREAD

**Issue by neerajbachani** [CircuitVerse/cv-frontend-vue#106]
Is your feature request related to a problem?
The docs for Image Annotation are present in the circuitVerse docs but its helplinks are not available in the simulator.

Describe the solution you'd like
Like other Elements, we need to add the helplink for the Image Annotation.

**As we can see the help button in properties section**
![Screenshot (1331)](https://user-images.githubusercontent.com/124370566/222968910-84c25c29-3b78-4510-813e-f9c6a404da31.png)

**The help link button is not present in Image Annotation.**
![Screenshot (1329)](https://user-images.githubusercontent.com/124370566/222969010-d2be542b-39b2-457f-bf1e-9058668ed9cf.png)

**Are you working on this? (Yes/No)**
yes

**Comment by akoolarni** [comment]
Can I help up with the issue please?
