### ISSUE TITLE
Using / for division outside of calc() is deprecated

### ISSUE THREAD

**Issue by kr-2003** [CircuitVerse/cv-frontend-vue#109]
**Describe the bug**
This is a bug while development.
Using / for division outside of calc() is deprecated and will be removed in Dart Sass 2.0.0.

**To Reproduce**
1. Setup the project on your local machine.
2. Run ```npm install``` and then ```npm run dev```.
3. You can see following deprecation warnings.
4. ***Screenshots***
<img width="1003" alt="Screenshot 2023-03-06 at 9 38 15 PM" src="https://user-images.githubusercontent.com/96587705/223165938-a3eeaaf9-195b-46ed-954c-31455e99a122.png">
<img width="995" alt="Screenshot 2023-03-06 at 9 38 37 PM" src="https://user-images.githubusercontent.com/96587705/223166038-07e26af9-9e37-49a6-beb8-c970fa6f6586.png">

**Expected behavior**
No deprecation warnings.

**Device Information [optional]:**
- OS: MacOS
- Editor: VSCode

**Are you working on this issue? (Yes)**

**Comment by Arnabdaz** [comment]
solved as of #214
