### ISSUE TITLE
Add Bengali language translation i18n

### ISSUE THREAD

**Issue by Arnabdaz** [CircuitVerse/cv-frontend-vue#113]
**Is your feature request related to a problem? Please describe.**
Currently there is only English and Hindi version of i18n available for the simulator

**Describe the solution you'd like**
Also add support for Bengali with i18n

**Describe alternatives you've considered**
Suggestions are welcome

**Additional context**
![image](https://user-images.githubusercontent.com/96580571/223507353-a1f06579-cb83-4178-ac9c-d29920c1b1fe.png)

**Are you working on this? (Yes)**

**Comment by DhairyaMajmudar** [comment]
@Arnabdaz I also want to add Marathi and Gujarati language shall I go ahead?

**Comment by Murdock9803** [comment]
@Arnabdaz @DhairyaMajmudar I like the idea of more languages support by Dhairya. I also want to add Telugu and Malayalam languages support. This will help students from south india. So shall I go ahead ?

**Comment by Arnabdaz** [comment]
i think we would be having something similar to https://www.transifex.com/ we can discuss regarding the same on circuitverse slack channel
