### ISSUE TITLE
fix: add gap between each timing-diagram

### ISSUE THREAD

**Issue by kr-2003** [CircuitVerse/cv-frontend-vue#115]
**Describe the bug**
Add spacing between each timing-diagram under under timing-diagram modal.

**To Reproduce**
1. Go to [https://circuitverse.netlify.app/simulator](https://circuitverse.netlify.app/simulator)
2. Click on Timing Diagram
3. See error
<img width="536" alt="Screenshot 2023-03-08 at 7 37 47 PM" src="https://user-images.githubusercontent.com/96587705/223734123-acce83f4-bcc9-4a73-a244-00c0b047434a.png">

**Expected behavior**
<img width="534" alt="Screenshot 2023-03-08 at 7 38 06 PM" src="https://user-images.githubusercontent.com/96587705/223734204-22c565c0-c7b6-44a6-ab81-bd307787da54.png">

**Are you working on this issue? Yes**

**Comment by AbdulBasit2733** [comment]
can i work on this issue.

**Comment by nisha-laur** [comment]
Hi, if this issue is still open . I would like to work on this . If you could assign this to me .

**Comment by disha1202** [comment]
Hi @nisha-laur, 
This issue has been fixed.
