### ISSUE TITLE
Setup CI/CD to automatically build and publish the site on GitHub Pages

### ISSUE THREAD

**Issue by dheerajdlalwani** [CircuitVerse/cv-frontend-vue#15]

**Comment by vish-han** [comment]
@dheerajdlalwani I would love to work on this Issue. Please Assign me

**Comment by vish-han** [comment]
Ok Thanks bhia, I will start soon🚀❤

**Comment by akshatcoder-hash** [comment]
#32 may fix this. Kindly review

**Comment by tachyons** [comment]
This is not needed for now as we have netlify integration
