### ISSUE TITLE
Cross/Close button not working in "Report an issue" section on simulator page

### ISSUE THREAD

**Issue by Mitali2700** [CircuitVerse/cv-frontend-vue#155]
**Describe the bug**
The cross/close button in the "Report an issue" section of the CircuitVerse frontend simulator page is not working. Clicking on it does not close the window.

**To Reproduce**
Go to the CircuitVerse frontend simulator page.
Click on the "Report an issue" button.
Fill out the form and click the "Submit" button.
Try to close the window using the cross/close button in the top right corner.
Notice that the window does not close.
Expected behavior
When clicked, the cross/close button should close the "Report an issue" window.

**Screenshots**
<br>
![Screenshot (10)](https://user-images.githubusercontent.com/78539161/229207538-ebadc1ff-5222-4a1f-b38b-d176b26a0763.png)
<br>
![Screenshot (11)](https://user-images.githubusercontent.com/78539161/229332307-01141215-d509-4c6c-8fd8-7c386173e0b6.png)

<br>
after clicking on **report button** it shows:

![Screenshot (12)](https://user-images.githubusercontent.com/78539161/229332316-b55a20e9-2db9-4f06-936f-68011d8e4d4d.png)

**Device Information:**
OS: Windows 11
Browser: Chrome

**Are you working on this issue? **
Yes

**Comment by Adarsh9306** [comment]
Hello @Mitali2700 if this issue is open can you please assign it to me? ... I am interested to work on this

**Comment by ishsarin** [comment]
Hi, if this is open can I contribute?

**Comment by Arnabdaz** [comment]
fixed by pr #174
