### ISSUE TITLE
Dark Mode Toggle

### ISSUE THREAD

**Issue by Mayank1170** [CircuitVerse/cv-frontend-vue#159]
## Describe the solution you'd like
The toggle button should be on the top right corner of the page.

## Describe alternatives you've considered
The user can manually switch between light and dark modes by clicking on a button or icon. This approach provides the most control to the user and is the most straightforward to implement.

## Additional context

![Screenshot from 2023-04-28 20-27-15](https://user-images.githubusercontent.com/98695348/235184053-8807c8b9-14f7-4563-8997-e41c62b12a37.png)

**Are you working on this? (Yes/No)**

**Comment by Nitishupkr** [comment]
i want to work on this
