### ISSUE TITLE
At the zoom section the zoom in and zoom out button are not in order they are little up and down which look bad

### ISSUE THREAD

**Issue by Nitishupkr** [CircuitVerse/cv-frontend-vue#164]
**Describe the bug**
At the zoom section the positive and negative button are not in order they are little up and down which look very bad we can align them in proper odder providing proper margin to it

**To Reproduce**
1. Go to  'https://circuitverse.netlify.app/simulator'
![circuitverse3](https://github.com/CircuitVerse/cv-frontend-vue/assets/95420063/7e1ddcd7-b214-4c81-95ba-b72e65390023)

**Expected behavior**
![Screenshot (24)](https://github.com/CircuitVerse/cv-frontend-vue/assets/95420063/ee0bfdea-d870-490b-81a9-85e13d2d81a2)

**Device Information [optional]:**

**Additional context**

**Are you working on this issue? (Yes/No)**
Yes

**Comment by Nitishupkr** [comment]
@devartstar see it

**Comment by Kuroo7** [comment]
Can you assign it to me

**Comment by ishsarin** [comment]
Hi, if this is open can I contribute?

**Comment by vatan45** [comment]
hi, if this is open i can raise a pr as i am on a verge of removing this issue

**Comment by nisha-laur** [comment]
Hi, if this issue is still open . I would like to work on this . If you could assign this to me .
