### ISSUE TITLE
Replace readme with project setup information 

### ISSUE THREAD

**Issue by tachyons** [CircuitVerse/cv-frontend-vue#190]
Current readme is about the initial gsoc project. It is no longer relevant for this project. We can provide more useful information on the readme file

**Comment by disha1202** [comment]
Can I work on this?

**Comment by tachyons** [comment]
Go ahead

**Comment by niladrix719** [comment]
@disha1202 are you still working on this?

**Comment by disha1202** [comment]
Yes @niladrix719
