### ISSUE TITLE
Hover animation not as expected

### ISSUE THREAD

**Issue by DhairyaMajmudar** [CircuitVerse/cv-frontend-vue#191]
**Describe the bug**
while hovering on the tabs present in the navbar its showing improper animation it must be corrected

**To Reproduce**
1. Go to https://circuitverse.netlify.app/simulatorvue
2. Hover on navbar tabs
3. See error

**Expected behavior**
The hover effect must be a bit better

**Screenshots**
![image](https://github.com/CircuitVerse/cv-frontend-vue/assets/124715224/01095da6-0fee-4846-8be1-903d31930379)

**Device Information [optional]:**
- OS: windows
- Browser FireFox
- Version Windows 11

**Additional context**

**Are you working on this issue? (Yes/No)**
YES

**Comment by DhairyaMajmudar** [comment]
@Prerna-0202 pls. review and assign this issue to me.

**Comment by Prerna-0202** [comment]
> @Prerna-0202 pls. review and assign this issue to me.

Could you please in a bit more detail, like how you want to change?

**Comment by DhairyaMajmudar** [comment]
> > @Prerna-0202 pls. review and assign this issue to me.
> 
> Could you please in a bit more detail, like how you want to change?

On hover the arrow svg get shifted in right side and also the underline is not showing a proper transition while hovering .

**Comment by nisha-laur** [comment]
Hi, if this issue is still open . I would like to work on this . If you could assign this to me .

**Comment by akoolarni** [comment]
I am ready to take the issue. Can I?

**Comment by pankaj-2503** [comment]
I don't think there modification is required as the hover effect is fine as on hover it creates a bar under links and removes the angular drop down. No need of any changes. Close this issue.
