### ISSUE TITLE
Navbar hover dropdown is going behind Circuit Elements

### ISSUE THREAD

**Issue by jaydip1235** [CircuitVerse/cv-frontend-vue#194]
**Describe the bug**
 Navbar hover dropdown is going behind Circuit Elements on mimimizing circuit elements and then maximizing it.

**To Reproduce**
1. Go to 'https://circuitverse.netlify.app/simulatorvue'
2. Minimize the Circuit elements using minus button
3. Again expand the Circuit Elements
4. Hover over the Project tab and notice that the dropdown is going behind, and not all options are visible even if you minimize the circuit element

**Expected behavior**
 The dropdown elements should come in front of Circuit Elements

**Screenshots**
<img width="302" alt="Screenshot 2023-11-18 at 7 19 25 PM" src="https://github.com/CircuitVerse/cv-frontend-vue/assets/65560026/95422bd9-5df7-4514-aacd-001ead185f6b">

https://github.com/CircuitVerse/cv-frontend-vue/assets/65560026/8a03e8c7-9dda-450e-9474-0e52bc22018c

**Device Information [optional]:**

**Additional context**

**Are you working on this issue? (Yes/No)**
Yes

**Comment by jaydip1235** [comment]
@vedant-jain03 @Prerna-0202 @Arnabdaz , Please assign this issue to me

**Comment by Prerna-0202** [comment]
Go ahead @jaydip1235
