### ISSUE TITLE
Removing Console Warnings   

### ISSUE THREAD

**Issue by DhairyaMajmudar** [CircuitVerse/cv-frontend-vue#196]
**Describe the bug**
While running the app in the local server several console errors / warnings are shown in the console.

**To Reproduce**
1. Run the app locally using the command `npm run dev`
2. Open the console and check the errors / warnings 

**Expected behavior**
The console must be free from warnings

**Screenshots**
![image](https://github.com/CircuitVerse/cv-frontend-vue/assets/124715224/7088c967-8fe5-478f-8b49-d26f66977d3c)

**Device Information [optional]:**
- OS: Linux - Debain 
- Browser : Firefox
- Version 22

**Additional context**

**Are you working on this issue? (Yes/No)**
Yes

**Comment by DhairyaMajmudar** [comment]
@tanmoysrt @Prerna-0202 Several console errors/warnings are noted this might be because of the old version of the font-awesome lib. ( **5.14.4** ) used in the project. 

PTAL and assign this issue to me. 

Thanks!

**Comment by disha1202** [comment]
Hi @DhairyaMajmudar 

There's already an existing issue for these warnings #188

**Comment by DhairyaMajmudar** [comment]
> Hi @DhairyaMajmudar
> 
> There's already an existing issue for these warnings #188

Thanks,  Shall I open a PR to solve this issue
