### ISSUE TITLE
In Render image container the " current view button" is too big for mobile view 

### ISSUE THREAD

**Issue by upsaurav12** [CircuitVerse/cv-frontend-vue#202]
**Describe the bug**
In render image box the "current view button " the button is too big when we see it on the mobile view especially when we change along height as well 

**To Reproduce**
1. Go to https://circuitverse.org/simulator
2. Click on "Download as image button "
3. See the "Current view button " in mobile view
![image](https://github.com/CircuitVerse/cv-frontend-vue/assets/116784047/8c78e633-b8fa-4458-bb69-8d3f48d4ef29)

**Expected behavior**
The button should not big in mobile view
![image](https://github.com/CircuitVerse/cv-frontend-vue/assets/116784047/3002ff43-eb55-49df-9e41-4f5575246b49)

**Screenshots**
![image](https://github.com/CircuitVerse/cv-frontend-vue/assets/116784047/185caa01-9406-4310-9a1d-a34bf16f93b3)

**Device Information [optional]:**

**Additional context**

**Are you working on this issue? Yes

**Comment by upsaurav12** [comment]
I want to work on this issue

**Comment by Arnabdaz** [comment]
@upsaurav12 this issue is related to the old simulator you can open issue for the same at [here](https://github.com/CircuitVerse/CircuitVerse) and close this issue.

**Comment by upsaurav12** [comment]
closing this issue
