### ISSUE TITLE
Context-menu id  is not responsive not displaying properly 

### ISSUE THREAD

**Issue by upsaurav12** [CircuitVerse/cv-frontend-vue#203]
**Describe the bug**
When you click right click on mouse inside the simulation area then is not responsive as we reduces the width 
but when i checked this when i clicked towards left in the whiteboard then it working fine
**To Reproduce**
1. Go to '.https://circuitverse.org/simulator'
2. Right Click on 'white-board '
3. Reduce the Width 

**Expected behavior**
It should display properly 

**Screenshots**
I don't know its sometime working sometime not 

https://github.com/CircuitVerse/cv-frontend-vue/assets/116784047/641d6ffc-da79-44da-b8ab-b87587b62aa3

**Device Information [optional]:**

**Additional context**

**Are you working on this issue? Yes

**Comment by rose2221** [comment]
@upsaurav12  i would like to work on this issue. i've already started working on it, i'll upload a draft PR for the same soon. Could you please assign me this issue?

**Comment by upsaurav12** [comment]
i am not the maintainer

**Comment by Arnabdaz** [comment]
@upsaurav12 this issue is related to the old simulator you can open issue for the same at [here](https://github.com/CircuitVerse/CircuitVerse) and close this issue.
