### ISSUE TITLE
bug: Red color bug when simulator button clicked 

### ISSUE THREAD

**Issue by upsaurav12** [CircuitVerse/cv-frontend-vue#213]
**Describe the bug**
When i clicked simulator button page renders red color bug occuring. 

**To Reproduce**
1. Go to 'https://circuitverse.org/'
2. Click on 'Simulator button' in nav-bar
3. See error

**Expected behavior**
It should display properly when clicked
**Screenshots**

https://github.com/CircuitVerse/cv-frontend-vue/assets/116784047/c5cc73ab-49c9-4564-aec9-baf2585ee1d3

**Device Information [optional]:**

**Additional context**
May be this is from my side

**Are you working on this issue? (Yes/No)

**Comment by Arnabdaz** [comment]
the simulator used in production is the old simulator you can open the issue for the same at [CircuitVerse main repo](https://github.com/CircuitVerse/CircuitVerse) and close this issue.

**Comment by upsaurav12** [comment]
so i have to open the same issue in main circuitverse repo??

**Comment by upsaurav12** [comment]
Closing the issue
