### ISSUE TITLE
fix: Content and button are not visible in svg option

### ISSUE THREAD

**Issue by upsaurav12** [CircuitVerse/cv-frontend-vue#217]
**Describe the bug**
In Simulator for converting the diagram to svg the buttons and contents are not visible like png,jpeg,bmp,gif

**To Reproduce**
1. Go to 'https://circuitverse.org/simulator'
2. Click on 'Download as image'
![image](https://github.com/CircuitVerse/cv-frontend-vue/assets/116784047/d86f713c-93aa-463b-8acc-5348dc0455b5)
3. Click on SVG option

**Expected behavior**
![image](https://github.com/CircuitVerse/cv-frontend-vue/assets/116784047/2090cd87-4679-44aa-afbb-f10df5ae7019)

**Screenshots**
![image](https://github.com/CircuitVerse/cv-frontend-vue/assets/116784047/2f3862b7-6e86-42a6-8bd5-b32df6d1b1eb)

**Device Information [optional]:**

**Additional context**
You can check from your side maybe this is from my side 

**Are you working on this issue? (Yes)**

**Comment by Arnabdaz** [comment]
This is a main simulator issue and is not present in the vue simualtor.

**Comment by upsaurav12** [comment]
where should i raise this issue ??

**Comment by upsaurav12** [comment]
closing this issue
