### ISSUE TITLE
Feat: Toggle Feature for the overflowed tabs

### ISSUE THREAD

**Issue by NayakPenguin** [CircuitVerse/cv-frontend-vue#222]
## Problem 

Increasing the number of tabs results in their descent, leading to a reduction in the main circuit space, unlike when fewer tabs are open.

<img width="1123" alt="Screenshot 2023-12-24 at 7 26 44 PM" src="https://github.com/CircuitVerse/cv-frontend-vue/assets/93304796/5f434614-5977-4091-9950-5fe3060e1772">

## Proposed Solution 

- [x]  Implement a toggle button in the top-right corner.
- [x]  Initially, display the first line of tabs by default.
- [x]  When the toggle button is clicked, reveal the remaining tabs in a dropdown fashion.
- [x]  Clicking the toggle button again or selecting the circuit space portion should revert the tabs to their default state.

#### Pre-toggle state
<img width="769" alt="Screenshot 2023-12-24 at 7 44 15 PM" src="https://github.com/CircuitVerse/cv-frontend-vue/assets/93304796/f57c3fde-c982-418c-ba78-f46921eaf4e9">

#### Post-toggle scenario
<img width="805" alt="Screenshot 2023-12-24 at 7 45 03 PM" src="https://github.com/CircuitVerse/cv-frontend-vue/assets/93304796/a66453cb-31df-4b43-8052-452914c73429">

### Are you working on this?
**YES**, I am working on this issue

**Comment by Arnabdaz** [comment]
@NayakPenguin you can start working on the issue.
