### ISSUE TITLE
Replace setInterval for checking of switching of tabs

### ISSUE THREAD

**Issue by devartstar** [CircuitVerse/cv-frontend-vue#23]
Since the properties panel content depends upon the tab/circuit selected.
We check for the switching of tabs every 0.1s.
In `ProjectProperty.vue` file
```
// checking if circuit or tab is switched
    setInterval(() => {
        if (circuitId.value != globalScope.id) {
            circuitName.value = globalScope.name
            circuitId.value = globalScope.id
        }
    }, 100)
```
Aim -
Need to replace `setInterval` with some better implementation.

**Comment by nikhilhvr** [comment]
Hey @disha1202 
Let me know if you're also working on this. Excited to contribute to this issue!
