### ISSUE TITLE
Hidden "Sign In" button 

### ISSUE THREAD

**Issue by Priyanshu-su30** [CircuitVerse/cv-frontend-vue#241]
**Describe the bug**
In the home page at top right corner the "Sign in" button is hidden.

**Expected behavior**
The "Sign in" button should be displayed properly.

**Screenshots**
![Screenshot (115)](https://github.com/CircuitVerse/cv-frontend-vue/assets/107869522/e247eab7-abea-46d6-a402-e690f459b6f9)

**Are you working on this issue? (Yes/No)**
Yes

**Comment by pankaj-2503** [comment]
Hey, this could be done so that button is differentiable then links by adding some backgrounds colors .
![image](https://github.com/CircuitVerse/cv-frontend-vue/assets/90036864/0a1eaa26-e362-492d-b03c-8d38c6980d7d)

**Comment by Priyanshu-su30** [comment]
@pankaj-2503 If you add background to the button it will look odd in the navbar.

**Comment by pankaj-2503** [comment]
@Priyanshu-su30   i thought  button should look different than  links  .
