### ISSUE TITLE
Document setup using stackblitz

### ISSUE THREAD

**Issue by tachyons** [CircuitVerse/cv-frontend-vue#258]
Stack blits can be used to develop cv-frontend without having to setup everything locally.

https://stackblitz.com/~/github.com/CircuitVerse/cv-frontend-vue

**Comment by DhairyaMajmudar** [comment]
That's good idea @tachyons shall i take this up

**Comment by niladrix719** [comment]
seems like the preview is failing for this link

**Comment by DhairyaMajmudar** [comment]
Very true its on both firefox and chrome.

**Comment by DhairyaMajmudar** [comment]
https://cvfrontendvue-3bdo--4000--22b9f6d5.local-corp.webcontainer.io/simulatorvue/   Try to use this on the then its working fine.
