### ISSUE TITLE
Feature: Search results in ElementsPanel should include "Matched Categories" section along with already available "Matched Elements"

### ISSUE THREAD

**Issue by Chandrachur67** [CircuitVerse/cv-frontend-vue#262]
## Is your feature request related to a problem? Please describe.

It's not an issue; rather, it's a feature. The search option in ElementsPanel gives elements whose names match the search input. For example, if we search for "Input" only two elements are shown as results, but there are a total 8 elements inside original "Input" category.

So I think that it would be even better if we could include one more section, i.e., "Matched Categories", that would list the categories that match the search input.
So if you search for "Input" :
- The "Matching elements will show two elements whose name matches with searchInput.
- The "Matching elements will show "Input" Category as an result, which can be expanded to get all the elements inside "Input" category.

![Screenshot 2024-01-18 at 12 15 07 AM](https://github.com/CircuitVerse/cv-frontend-vue/assets/97349505/9c47fe78-aa30-485d-be1e-3a09eca6770b)
![Screenshot 2024-01-18 at 12 15 15 AM](https://github.com/CircuitVerse/cv-frontend-vue/assets/97349505/860c3acb-5786-41bf-a05d-f27ea563c3af)

## Describe the solution you'd like

I think adding one additional section "Matched Categories" along with "Matching Elements" will be a good Idea.

![Screenshot 2024-01-18 at 12 26 07 AM](https://github.com/CircuitVerse/cv-frontend-vue/assets/97349505/3cc5d660-899c-47b3-b07e-c49ce29c8d2e)

## Describe alternatives you've considered
N/A

## Additional context
N/A

## Are you working on this? (Yes/No)
Yes

**Comment by Chandrachur67** [comment]
@Arnabdaz  @Prerna-0202  please take a took at this. Assign this to me if possible. I have already started working on this.
Thanks again.

**Comment by Arnabdaz** [comment]
@tachyons wdyt ?

**Comment by Chandrachur67** [comment]
@Arnabdaz  @tachyons is there any update? Can I work on this? I believe this would be great value addition both in functionality and user experience.

**Comment by tachyons** [comment]
Looks good to me

**Comment by Chandrachur67** [comment]
I have almost done with the feature.
 
However I like to clarify two things. 
1. I am thinking of **not** adding a heading "Matched Categories", I believe it will look clear without this. 
   This is a image of the design I am proposing. Is this ok?
<img width="262" alt="Screenshot 2024-01-20 at 1 34 26 PM" src="https://github.com/CircuitVerse/cv-frontend-vue/assets/97349505/0fddb0dd-8a5e-46db-83f6-bd062242ce95">





2. Regarding the code 
Should I add a new ```v-expansion-panel``` below the 'search results', that will render matched categories when there is some matching categories or should I modify the code already available to show all categories when searchInput is empty and matched categories when searchInput is not empty.

My code is ready. I can create a PR as soon as you assign it to me.
Thank you.

**Comment by Arnabdaz** [comment]
if you already have implemented a solution you can make a pr we can test and make changes accordingly else we can discuss the best approach.

**Comment by Chandrachur67** [comment]
Ok thanks. I will create a pr very soon.
