### ISSUE TITLE
Drop JQuery dependency

### ISSUE THREAD

**Issue by tachyons** [CircuitVerse/cv-frontend-vue#27]
Though we removed jquery ui, we still have jquery in our codebase. which need to be removed and use native DOM methods

**Comment by disha1202** [comment]
Hi @tachyons, 
I would like to work on this.

**Comment by tachyons** [comment]
@disha1202 You can start working on this, but since jquery is used in several files, PR will be very huge. So I suggest you create PRs with changes per file. Also multiple people can work on this if you cab mention which file/files you want to work on

**Comment by disha1202** [comment]
Sure @tachyons, I would like to start with Verilog2CV.js file.

**Comment by snehalshah8429** [comment]
@tachyons can I work on this?

**Comment by snehalshah8429** [comment]
@tachyons  I would like to contribute on this

**Comment by snehalshah8429** [comment]
@disha1202 do you need any help in this project?

**Comment by PRO-BROS** [comment]
Very well. Facing the same issue but now resolved on my [site](https://prhocoding.com/)

**Comment by disha1202** [comment]
@tachyons, I've removed JQuery dependency in Verilog2CV.js file.
Please take a look.

**Comment by GarvitSinghal47** [comment]
@tachyons and @devartstar as there are multiple js files in which there is still jquery present in them I would like to work and help remove jquery from some of the files.

**Comment by GarvitSinghal47** [comment]
Hey @tachyons  as i discussed in the slack i am currently working on circuit.js file.

**Comment by niladrix719** [comment]
i am working on action.js

**Comment by antriksh-9** [comment]
Hey @Arnabdaz @Prerna-0202 I have worked on PR #226.

**Comment by antriksh-9** [comment]
I am working on testbench.js file.

**Comment by antriksh-9** [comment]
I am working on tutorials.js file.

**Comment by antriksh-9** [comment]
I am working on ux.js file.

**Comment by antriksh-9** [comment]
I am working on canvasApi.js file.

**Comment by tachyons** [comment]
Note: when you move transitions like fade from JQuery, use [Vue transitions](https://vuejs.org/guide/built-ins/transition) instead of trying to implement it vanilla JS.
