### ISSUE TITLE
🐞 Bug: [ Corner Triangular Edge Display Issue Of Logic Gates ]

### ISSUE THREAD

**Issue by Darshan808** [CircuitVerse/cv-frontend-vue#310]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Describe the bug

When viewing circuit elements such as OR Gate, NOR Gate, and X-OR Gate in the simulator , their upper edge appears slightly messed up on default zoom. This issue affects the UI as it causes the corners of these gates to flicker and change their appearance when the position of gates is changed.

### Steps to Reproduce

1. Open simulator page
2. Add OR Gate to the simulation Area.
3. Keep on changing the position of OR gate.
4. Observe the upper edge of the gate at default zoom level.

### Expected Behavior

The corner triangular edges of the gates should appear smooth and consistent at all zoom levels, without any distortion or flickering at every position.

### Screenshots

![Screenshot 2024-05-13 174822](https://github.com/CircuitVerse/cv-frontend-vue/assets/127468609/ccaa6ae8-3806-4be0-9b99-4dcbf262f8be)
![Screenshot 2024-05-13 174850](https://github.com/CircuitVerse/cv-frontend-vue/assets/127468609/f6773c79-bc57-4a92-9813-be261c306c4f)
![Screenshot 2024-05-13 203220](https://github.com/CircuitVerse/cv-frontend-vue/assets/127468609/0f254134-e8b3-4222-a274-ca7f9247542f)

### Is the faced issue/bug related to the Vue simulator?

Yes

### Used Vue simulator with or without backend?

Without Backend

### Is the bug present only on the dev server, the build, or both?

Both

### Are you working on this issue?

Yes

**Comment by JoshVarga** [comment]
https://github.com/CircuitVerse/cv-frontend-vue/pull/311 was merged fixing the issue
