### ISSUE TITLE
refactor: Report an Issue component and fix cancel button functionality 

### ISSUE THREAD

**Issue by palashb01** [CircuitVerse/cv-frontend-vue#36]
- [ ]  **Migrate the Report_an_Issue into its own component**
- [ ]  **Replace Jquery with Vue**
- [ ]  **Replace Ajax with fetch**
- [ ]  **Fix cancel button functionality**

- Below is the demo video for the same.

https://user-images.githubusercontent.com/66828942/209968320-5673c1b1-9b3b-454c-a7ff-4322f0ec5e40.mp4

- Below is the image of the pop-up

![circuitverse_issue](https://user-images.githubusercontent.com/66828942/209968408-9ef4dd89-6bbd-44c3-950d-dcff262f43ca.png)

Are you working on this Issue ?
**YES**

**Comment by Arnabdaz** [comment]
fixed by #174
