### ISSUE TITLE
Update the readme with setup guide

### ISSUE THREAD

**Issue by disha1202** [CircuitVerse/cv-frontend-vue#41]
Update the readme with guide to setup the project on local machine.

**Comment by Amanshenoy008** [comment]
Hey, i would like to work on this...

**Comment by disha1202** [comment]
> Hey, i would like to work on this...

@Amanshenoy008 
Sure go ahead

**Comment by Amanshenoy008** [comment]
What's the commit message format ....

**Comment by disha1202** [comment]
> What's the commit message format

Please refer to this https://www.conventionalcommits.org/en/v1.0.0/

**Comment by Avi-88** [comment]
Hi @disha1202 , seems like there was already a open PR for this issue. I am extremely sorry @Amanshenoy008 I didn't notice it as it wasn't  linked with the issue. If you were still working on this please let me know I'll close mine, thanks and once again sorry for not noticing before creating the PR

**Comment by Amanshenoy008** [comment]
oh well , itz fine .

**Comment by disha1202** [comment]
Closing as duplicate of #190

**Comment by tachyons** [comment]
Thanks for raising this issue, I missed this issue when created new one

**Comment by disha1202** [comment]
> Thanks for raising this issue, I missed this issue when created new one

No issue
