### ISSUE TITLE
Creating New Circuit dialog box - default name should be selected

### ISSUE THREAD

**Issue by devartstar** [CircuitVerse/cv-frontend-vue#55]
**Describe the bug**

**To Reproduce**
1. Go to tabsbar
2. Click on `+` icon
3. New Circuit Dialog Box appears
4. instead of placeholder -> default circuit name should be selected

**Expected behavior**
compare with [circuitverse site](www.circuitverse.org)

**Screenshots**

https://user-images.githubusercontent.com/61665451/211151728-9f351ec4-4e1d-4169-84a7-2dc3e7ddb811.mov

**Device Information [optional]:**

**Additional context**

**Are you working on this issue? (Yes/No)**
No

**Comment by ashutosh887** [comment]
@devartstar Is this Issue resolved? I would like to contribute!

**Comment by sushilpandeyy** [comment]
@devartstar I want to contribute in this issue please assign it to me

**Comment by ashutosh887** [comment]
@sushilpandeyy I don't think this is active Repository

**Comment by Adarsh9306** [comment]
HELLO I WANT TO CONTRIBUTE IF THIS IS STILL OPEN PLEASE ASSIGN IT TO ME

**Comment by Arnabdaz** [comment]
fixed #170
