### ISSUE TITLE
Creating a new circuit after deleting a circuit from `delete Circuit`  button causes an error.

### ISSUE THREAD

**Issue by palashb01** [CircuitVerse/cv-frontend-vue#61]
**Describe the bug**
- If a circuit is deleted by clicking the `delete circuit button` in the properties panel, an error warning appears when attempting to create a new circuit.

**Demo:**
![circuitverse_bug](https://user-images.githubusercontent.com/66828942/211322113-8bc0c160-e4f6-4f00-b676-17bdc2085e3c.gif)

**Expected behavior**
- the `delete button` should give a warning, if there is only one circuit.
- Creation of a new circuit should work properly without giving errors.

**Device Information [optional]:**

**Are you working on this issue? (Yes/No)**
**NO**

**Comment by palashb01** [comment]
> hello @palashb01 , I would like to work on this issue
>  

Sure go ahead 👍

**Comment by chetanjangir0** [comment]
@palashb01 Issue resolved, Please review

**Comment by Arnabdaz** [comment]
fixed #170
