### ISSUE TITLE
Exit preview button not working 

### ISSUE THREAD

**Issue by GarvitSinghal47** [CircuitVerse/cv-frontend-vue#63]
**Describe the bug**
The exit full preview button is not working.

**Expected behavior**
on clicking the full-screen btn quick panel should be hidden and an exit full preview button needs to be shown.
 
**Screenshots**
![ezgif com-gif-maker](https://user-images.githubusercontent.com/82756460/212134046-ae115803-beab-46e9-b615-5d444dc5a922.gif)

**Device Information [optional]:**
- OS: [Windows]
- Browser [Brave]

**Are you working on this issue? Yes**

**Comment by Arnabdaz** [comment]
fixed by #175
