### ISSUE TITLE
Error while creating a new circuit after deleting

### ISSUE THREAD

**Issue by GarvitSinghal47** [CircuitVerse/cv-frontend-vue#68]
**Describe the bug**
when we try to add a new circuit after deleting any circuit from the delete circuit button then it show error as displayed below.

**To Reproduce**
1. Go to 'circuitverse simulator'
2. Click on 'plus icon to generate some new circuit and create some circuit'.
3. Then go to any circuit and delete it using delete circuit button .
4. Then using plus icon try to add some new circuit in it .
5. See error

**Screenshots**
![ezgif com-gif-maker](https://user-images.githubusercontent.com/82756460/215041149-e0dc8151-669b-45d7-bd81-e578e3ba3900.gif)

**Are you working on this issue?  No**

**Comment by jaydip1235** [comment]
@vedant-jain03 @Arnabdaz @Prerna-0202 , Can I work on this issue ?

**Comment by Arnabdaz** [comment]
fixed by #170
