### ISSUE TITLE
bug(ui): Quick-Button is overlapping the Navigation bar

### ISSUE THREAD

**Issue by niladrix719** [CircuitVerse/cv-frontend-vue#71]
**Describe the bug**
Quick-Button is overlapping the Navigation bar

**To Reproduce**
1. Go to 'https://circuitverse.netlify.app/simulator'
2. Decrease the screen to enable the hamburger icon
3. Click on 'hamburger icon'
4. See error 'The quick button is overlapping'

**Expected behavior**
The Quick-button should not overlap the Navigation bar

**Screenshots**

![Screenshot from 2023-02-01 15-39-09](https://user-images.githubusercontent.com/91966855/216015514-e8213e70-b562-407b-b3fc-c0acb2396ace.png)

- OS: [Ubuntu 22]
- Browser [chrome]
- Version [v22]

**Are you working on this issue? (Yes/No)**
Yes

**Comment by Mayank1170** [comment]
Hey @niladrix719 !!
I'll already start working on this issue and actually capture the issue in the code..
so can you please assign it to me ?

**Comment by Mayank1170** [comment]
Hey @niladrix719 
Am i doing right ?

[Screencast from 2023-02-10 21-30-35.webm](https://user-images.githubusercontent.com/98695348/218137836-4054f05b-76ee-46f0-8d85-ca28d0cb0a6f.webm)

**Comment by DhairyaMajmudar** [comment]
@niladrix719 shall I take up this?
Thank you.
