### ISSUE TITLE
Disable text underline on hovering items in Nav Menu

### ISSUE THREAD

**Issue by devartstar** [CircuitVerse/cv-frontend-vue#80]
**Describe the bug**
On hovering over the menu items in Navbar, it has underline as well as border bottom.

**Solution**
Only border bottom should be present.

**To Reproduce**
Steps to reproduce the behaviour:
- Go to [cv-frontend-vue](https://circuitverse.netlify.app/)
- hover on the items in Navbar
- compare the difference with [current simulator](https://circuitverse.org/simulator)

![Image](https://user-images.githubusercontent.com/61665451/221711299-62304f3b-f45b-46f8-a931-3c72073887c0.png)

**Comment by rockharshitmaurya** [comment]
I'm reaching out to request that you could assign me this particular issue, I'm interested in working on. Specifically, I'm interested in tackling issue #80. I believe this issue aligns with my skills and experience, and I'm excited to contribute to the project in this way.

I would appreciate it if you could assign me this issue and provide any guidance or suggestions for getting started.

Thank you for your time and consideration.

**Comment by kr-2003** [comment]
I want to work on this issue! Can you assign this to me?

**Comment by GaganMeshram123** [comment]
hey @Prerna-0202 and @vedant-jain03  Is these issue open to contribute ?
i would like to contribute on these issue.

**Comment by Arnabdaz** [comment]
This issue is already closed as completed
