### ISSUE TITLE
Padding and Alignment issue in Tabsbar

### ISSUE THREAD

**Issue by devartstar** [CircuitVerse/cv-frontend-vue#81]
**Describe the bug**

Things to fix -

- Tabsbar height
- cross icon
- alignment of circuit name with cross icon
- plus icon size and alignment

**To Reproduce**

Steps to reproduce the behaviour:

- Go to [cv-frontend-vue](https://circuitverse.netlify.app/)
- check for the styling issue in tabsbar
- compare the difference with [current simulator](https://circuitverse.org/simulator)

![Image](https://user-images.githubusercontent.com/61665451/221712420-b95a70d2-3d52-405a-831c-1fd927c5b203.png)

**Comment by JayashTripathy** [comment]
I want to work on this.

**Comment by rockharshitmaurya** [comment]
Hey @devartstar I would love to work on this issue, could you please assign me this issue

**Comment by devartstar** [comment]
Hi @rockharshitmaurya since @JayashTripathy asked first, let him go forward with this. 
Will open more issues soon, you can pick them up.

**Comment by Rajeevjewar** [comment]
Is this issue still opens, If it is so please assign it to me. I want to work on this issue.

**Comment by harshsharma-11** [comment]
@devartstar is this still open please let me know i want to work on it

**Comment by souravgope** [comment]
@devartstar i want to work on this issue please assign me

**Comment by krishnagitcontri** [comment]
Hey @devartstar is the issue still open ?

**Comment by uddeshyatyagi123** [comment]
@devartstar , please assign me, I want to work on this issue.

**Comment by ShivamPande18** [comment]
hey @devartstar if it is open, I would like to work on this
