### ISSUE TITLE
Custom Theme Dialog box styling

### ISSUE THREAD

**Issue by devartstar** [CircuitVerse/cv-frontend-vue#82]
**Describe the bug**
correct the ui of the `custom theme` dialog box.

**To Reproduce**
Steps to reproduce the behaviour:

- Go to [cv-frontend-vue](https://circuitverse.netlify.app/)
- From Navbar hover on Tools
- Select Themes from dropdown
- Select Custom theme
- compare the difference with [current simulator](https://circuitverse.org/simulator)

current -

![Image](https://user-images.githubusercontent.com/61665451/221712955-0c12b9d9-39be-42db-90a2-b0e54bb1fd63.png)

expected -

![Image](https://user-images.githubusercontent.com/61665451/221712996-a983e888-aac9-4c7d-adc1-b8947f9647bf.png)

**Comment by thisiskaransgit** [comment]
Hey @devartstar, I would like to work on this one!

**Comment by devartstar** [comment]
@thisiskaransgit sure go ahead.

**Comment by kr-2003** [comment]
Hey @devartstar, is this issue still open. Can i work on this?
