### ISSUE TITLE
Toggling in and out of Preview Mode

### ISSUE THREAD

**Issue by devartstar** [CircuitVerse/cv-frontend-vue#83]
**Describe the bug**
Currently on going to `Preview mode`, the quick button does not disappear and the `Exit Preview button` does not appear. 
To exit you can use `Esc button`.

**To Reproduce**
Steps to reproduce the behaviour:

- Go to [cv-frontend-vue](https://circuitverse.netlify.app/)
- From quick button panel
- Select preview option
- compare the difference with [current simulator](https://circuitverse.org/simulator)

![Image](https://user-images.githubusercontent.com/61665451/221713814-62858ef2-2c33-4cb6-9058-0f4c8efbdbdd.png)

**Comment by GarvitSinghal47** [comment]
@devartstar i have already solve this issue and raised a pr previous month regarding this , have a look at it , i think my pr will resolve the issue.

**Comment by devartstar** [comment]
@GarvitSinghal47  Thanks for notifying!
