### ISSUE TITLE
Panning effect of canvas not working

### ISSUE THREAD

**Issue by devartstar** [CircuitVerse/cv-frontend-vue#84]
**Describe the bug**
On panning (press and drag) the circuit elements(simulationArea) moves but the canvas grids(backgroundArea) does not move.

**To Reproduce**
Steps to reproduce the behaviour:

- Go to [cv-frontend-vue](https://circuitverse.netlify.app/)
- add some circuit elements
- checkout the pan mouse event
- compare the difference with [current simulator](https://circuitverse.org/simulator)

https://user-images.githubusercontent.com/61665451/221715169-9a08f5e4-d953-49b9-b7e0-3b849b03aa3e.mov

**Comment by Arnabdaz** [comment]
@devartstar may I work on this?

**Comment by vedant-jain03** [comment]
> @devartstar may I work on this?

Sure, go ahead!
