### ISSUE TITLE
404 Error on Non-Root Vue Router Pages Hosted on Netlify

### ISSUE THREAD

**Issue by rockharshitmaurya** [CircuitVerse/cv-frontend-vue#89]
## Is your feature request related to a problem? Please describe.
I have discovered an issue on a GitHub organization's repository. The issue pertains to a link provided on the repository, which allows contributors to explore their projects. However, upon refreshing the page, users receive a 404 error. This issue arises because the project uses Vue Router and is hosted on Netlify.

Specifically, Vue Router handles routing on the client-side (browser), and when a non-root page is visited (e.g., https://yoursite.netlify.com/login), Netlify (server-side) cannot handle the route. This results in a 404 error, which can be confusing and frustrating for users.
## Describe the solution you'd like
To fix the issue with the 404 error on non-root Vue Router pages hosted on Netlify, we can use Netlify's _redirects file. This file allows Netlify to handle URLs that are not handled on the client-side.

To create the _redirects file, go to the public folder of your app and create a file named _redirects. Then, add the following line of code to the file:

/* /index.html 200

This code redirects all requests to the root of your site, which allows Vue Router to handle the routing correctly. With this fix, users should no longer receive 404 errors when refreshing non-root pages on your site.

## Additional context

https://user-images.githubusercontent.com/46915044/222068709-fd7af824-70b0-4705-bfac-2867eac8eab9.mp4

## Are you working on this? (Yes/No)

Yes, I Have fixed The Issue if You think this is an issue, can I make a PR for the same?

**Comment by Arnabdaz** [comment]
fixed
