### ISSUE TITLE
Extra Underline in Sign in button

### ISSUE THREAD

**Issue by ShivamKaushik316** [CircuitVerse/cv-frontend-vue#93]
**Describe the bug**
The Sign in button in the navbar have 2 underlines when hovered

**Expected behavior**
Sign in button should have only one underline when hovered

**Screenshots**
I
![BEFORE-CIRUITVERS](https://user-images.githubusercontent.com/105926192/222668231-40f81555-25ba-4d58-8258-af06a4d3c19e.png)

**Device Information [optional]:**
- OS: Windows 10
- Browser : Chrome

**Additional context**

**Are you working on this issue? Yes

**Comment by ShivamKaushik316** [comment]
can i work on this issue ?

**Comment by ShivamKaushik316** [comment]
Can  I work on this issue ?

**Comment by devartstar** [comment]
This is solved so closing it.
